# Generated by Django 6.0 on 2026-01-17 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clsbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clsbook.student"
            ),
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="is_active_day",
        ),
        migrations.CreateModel(
            name="ClassDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "class_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_days",
                        to="clsbook.classbook",
                    ),
                ),
            ],
            options={
                "unique_together": {("class_book", "date")},
            },
        ),
    ]
