# Generated by Django 6.0 on 2026-01-19 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clsbook", "0002_alter_attendancerecord_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classbook",
            unique_together={("class_name", "section", "created_by")},
        ),
    ]
