# Generated by Django 6.0 on 2026-01-31 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the person contacting", max_length=200
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for response", max_length=254
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Brief subject of the inquiry", max_length=300
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("support", "Technical Support"),
                            ("feedback", "Feedback"),
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("other", "Other"),
                        ],
                        default="general",
                        help_text="Type of inquiry",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Detailed message content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        help_text="Current status of the inquiry",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the message was submitted",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update time"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of submitter", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent"),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether admin has read the message"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes from admin"),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="contact_con_created_00b9df_idx"
                    ),
                    models.Index(
                        fields=["status"], name="contact_con_status_fa3e24_idx"
                    ),
                    models.Index(
                        fields=["message_type"], name="contact_con_message_83810e_idx"
                    ),
                ],
            },
        ),
    ]
